WHATS_APP_PHONE_NUMBER = "13001234567"
WHATS_APP_PHONE_PASSWORD = "xxxxxxxxxxxxxxxxxxxxxxxxxxxx"

CREDENTIALS = (WHATS_APP_PHONE_NUMBER, WHATS_APP_PHONE_PASSWORD)

MYSQL_USER = "superroot"
MYSQL_PASSWORD = "Secrets##"